### ISSUE TITLE
Promise.done is deprecated.

### ISSUE THREAD

**Issue by suda** [spark/spark-dev#135]
Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done
```
Promise.done (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1052:5)
CompileErrorsView.confirmed (/Users/particle/.atom/packages/spark-dev/lib/views/compile-errors-view.coffee:99:15)
CompileErrorsView.confirmSelection (/Users/particle/.atom/packages/spark-dev/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
space-pen-li.<anonymous> (/Users/particle/.atom/packages/spark-dev/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19)
HTMLOListElement.jQuery.event.dispatch (/Users/particle/.atom/packages/spark-dev/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4435:9)
HTMLOListElement.elemData.handle (/Users/particle/.atom/packages/spark-dev/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4121:28)
```

**Comment by Kielkopf** [comment]
**Atom now uses ES6 Promises instead of Q. Call promise.then instead of promise.done**
Report Issue
Promise.done - /usr/lib/atom/src/atom-environment.js:1431:3
CompileErrorsView.confirmed - /home/andreas/.atom/packages/particle-dev/lib/views/compile-errors-view.js:80:12
CompileErrorsView.confirmSelection - /home/andreas/.atom/packages/console-panel/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21
HTMLLIElement.<anonymous> - /home/andreas/.atom/packages/console-panel/node_modules/atom-space-pen-views/lib/select-list-view.js:139:19
HTMLOListElement.dispatch - /home/andreas/.atom/packages/console-panel/node_modules/jquery/dist/jquery.js:4435:9
HTMLOListElement.elemData.handle - /home/andreas/.atom/packages/console-panel/node_modules/jquery/dist/jquery.js:4121:28
